version: '3.8'  # or the latest version
services:
  nginx:
    image: nginx:latest
    volumes:
      # - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Ensure the path is correct
      # - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Ensure the path is correct
      - ./conf:/etc/nginx/conf.d:ro
      - ./root/html:/usr/share/nginx/html:ro
    ports:
      - "8001:80"
    restart: always
